app:
  name: "Academic Writing Assistant"
  version: "1.0.0"
  api_v1_str: "/api/v1"

openai:
  models:
    default: "gpt-4o-mini"
    alternatives:
      - "gpt-4o"
      - "gpt-4"
  settings:
    max_tokens: 2000
    temperature: 0.7
    timeout: 30  # seconds
    system_prompts:
      default: "You are a helpful academic writing assistant."
      writing: "You are an expert academic writing assistant, trained to help with research papers, theses, and academic publications."
      citations: "You are a citation expert, helping with proper academic citations and references."
      research: "You are a research assistant, helping with literature review and research methodology."

rate_limits:
  window: 3600  # 1 hour in seconds
  tiers:
    free: 10
    basic: 50
    premium: 200
    unlimited: 1000

security:
  algorithm: "HS256"
  access_token_expire_minutes: 11520  # 8 days

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://localhost:5174"
