"""Add collaboration and comments tables

Revision ID: f4e2159a6d0e
Revises: cd1131979c91
Create Date: 2024-11-23 08:59:58.399196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e2159a6d0e'
down_revision = 'cd1131979c91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
